##############################
#                            #
#          Autostart         #
#                            #
##############################

# =================================================
# Filtre lumière bleue (wlsunset)
# Notifications (swaync)
# gnome-keyring-daemon
# Verrouillage auto (swayidle)
# protonmail-bridge
#
# Les outils précédent ont été ajouter à systemd --user
#
# =================================================

# Wallpapers
exec-once=swaybg -i ~/.wallpapers/662412-vanilla-arch-wallpaper-linuxart.png 

# Lancement au démarrage
exec-once=kitty --class kitty-1 --directory $HOME sh -c "tmux"
# exec-once=perplexity

# exec-once=kitty --class kitty-2 --directory $HOME
exec-once=kitty --class kitty-mon --directory $HOME
exec-once=chromium
exec-once=gtk-launch chrome-hnpfjngllnobngcgfapefoaidbinmjnm-Default
exec-once=gtk-launch 
exec-once=thunderbird
exec-once=spotify-launcher
exec-once=waybar
exec-once=proton-pass

# Presse-papier
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store

# Idle
exec-once=swayidle -w timeout 300 'swaylock -f -c 000000' timeout 360 'systemctl suspend' before-sleep 'swaylock -f -c 000000'
