##############################
#                            #
#          Autostart         #
#                            #
##############################

# =================================================
# Filtre lumière bleue (wlsunset)
# Notifications (swaync)
# gnome-keyring-daemon
# Verrouillage auto (swayidle)
# protonmail-bridge
# cliphist
# proton-pass
# exec-once=swayidle -w timeout 300 '~/.config/mango/scripts/lock.sh' timeout 310 'wlopm --off "*"' resume 'wlopm --on "*"' before-sleep '~/.config/mango/scripts/lock.sh'
# Les outils précédent ont été ajouter à systemd --user
#
# =================================================

# Wallpapers
exec-once=swaybg -i ~/.wallpapers/arch_rainbow.jpg

# Lancement au démarrage
exec-once=kitty --class kitty-1 
exec-once=kitty --class kitty-2
exec-once=kitty --class kitty-3
exec-once=kitty --class kitty-mon --directory $HOME
exec-once=chromium
exec-once=gtk-launch chrome-hnpfjngllnobngcgfapefoaidbinmjnm-Default
exec-once=gtk-launch 
exec-once=thunderbird
exec-once=spotify-launcher
exec-once=waybar
exec-once=AppFlowy
