##############################
#                            #
#          Autostart         #
#                            #
##############################

# =================================================
# Filtre lumière bleue (wlsunset)
# Notifications (swaync)
# gnome-keyring-daemon
# Verrouillage auto (swayidle)
# protonmail-bridge
#
# Les outils précédent ont été ajouter à systemd --user
#
# =================================================

# Wallpapers
exec-once=swaybg -i ~/.wallpapers/662412-vanilla-arch-wallpaper-linuxart.png 

# Lancement au démarrage
exec-once=kitty --class kitty-1 --directory $HOME
exec-once=perplexity
exec-once=kitty --class kitty-2 --directory $HOME
exec-once=chromium
exec-once=thunderbird
exec-once=spotify-launcher
exec-once=waybar
exec-once=proton-pass

# Presse-papier
exec=wl-paste --watch clipvault store 
exec=wl-paste --type image/png --watch clipvault store

# Idle
exec-once=swayidle -w timeout 300 'swaylock -f -c 000000' timeout 301 'systemctl suspend' before-sleep 'swaylock -f -c 000000'
