##############################
#                            #
#     Binds Applications     #
#                            #
##############################

# Applications principales 
binds=SUPER,Return,spawn,kitty
binds=SUPER+Shift,b,spawn,blueman-manager
binds=SUPER,b,spawn,chromium
binds=SUPER+Shift,f,spawn,firefox
binds=SUPER+Shift,XF86Assistant,spawn,perplexity
binds=SUPER,m,spawn,spotify-launcher
binds=SUPER+Shift,b,spawn,blueman-manager
binds=SUPER+Ctrl,l,spawn,swaylock
binds=SUPER+Ctrl,e,spawn,wofi --cache-file=/dev/null -Dimage_size=26 -Dynamic_lines=true --location top --yoffset=10 --width=600 --height=300 --gtk-dark --show drun
binds=SUPER,t,spawn,thunderbird
binds=SUPER+Shift,p,spawn,proton-pass
binds=SUPER+Shift,m,spawn,protonmail-bridge
binds=SUPER+Shift,v,spawn,virt-manager
binds=SUPER+Shift,t,spawn,thunar
binds=alt,p,toggle_named_scratchpad,Proton Pass,none,proton-pass
binds=SUPER,v,spawn,~/.config/mango/scripts/copypast
binds=NONE,Print,spawn,~/.config/mango/scripts/screenshot-clip.sh

