##############################
#                            #
#     Binds Applications     #
#                            #
##############################

# Applications system
binds=SUPER,Return,spawn,kitty
binds=SUPER+SHIFT,b,spawn,blueman-manager
binds=SUPER+SHIFT,p,spawn,proton-pass
binds=ALT,p,toggle_named_scratchpad,Proton Pass,none,proton-pass
binds=SUPER+SHIFT,m,spawn,protonmail-bridge
binds=SUPER+CTRL,l,spawn,swaylock
binds=SUPER+CTRL,e,spawn,wofi --cache-file=/dev/null -Dimage_size=26 -Dynamic_lines=true --location top --yoffset=10 --width=600 --height=300 --gtk-dark --show drun
binds=SUPER,v,spawn,~/.config/mango/scripts/copypast
binds=NONE,Print,spawn,~/.config/mango/scripts/screenshot-clip.sh
binds=SUPER+CTRL,f,spawn,AppFlowy
binds=SUPER+CTRL+SUPER,g,spawn,gimp

# Browsers & net
binds=SUPER,b,spawn,chromium
binds=SUPER+SHIFT,f,spawn,firefox
binds=SUPER,t,spawn,thunderbird

# IA's
binds=SUPER,p,spawn,perplexity
binds=SUPER,m,spawn,spotify-launcher

# Virtualisation
binds=SUPER+SHIFT,v,spawn,virt-manager

# Fichiers
binds=SUPER+SHIFT,t,spawn,thunar
binds=ALT,y,spawn,kitty --class kitty-yazi -- sh -c "yazi" 

