##############################
#                            #
#         Binds sys          #
#                            #
##############################

# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# Layout Bindings
# scrolle5 layout
binds=ALT,e,set_proportion,0.5
binds=ALT+SHIFT,e,set_proportion,1
binds=SUPER,x,switch_proportion_preset,

# switch layou5
binds=SUPER,n,switch_layout

# reload config
binds=SUPER,r,reload_config
binds=SUPER+CTRL,w,~/.config/waybar/scripts/restartWaybar.sh

# exit
binds=SUPER+CTRL,q,quit
binds=SUPER,q,killclient

# Brightness
bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl set +2%
bind=SHIFT,XF86MonBrightnessUp,spawn,brightnessctl set 100%
bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl set 2%-
bind=SHIFT,XF86MonBrightnessDown,spawn,brightnessctl set 10%

# Volume
bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 2%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 2%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=SHIFT,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SOURCE@ toggle

