##############################
#                            #
#    Navigation bindings     #
#                            #
##############################

# switch window focus
binds=SUPER,Tab,focusstack,next
binds=SUPER,Left,focusdir,left
binds=SUPER,Right,focusdir,right
binds=SUPER,Up,focusdir,up
binds=SUPER,Down,focusdir,down

# swap window
binds=SUPER+SHIFT,Up,exchange_client,up
binds=SUPER+SHIFT,Down,exchange_client,down
binds=SUPER+SHIFT,Left,exchange_client,left
binds=SUPER+SHIFT,Right,exchange_client,right

# switch window status
binds=SUPER,g,toggleglobal,
binds=SUPER,Tab,toggleoverview,
binds=SUPER,backslash,togglefloating,
binds=SUPER,a,togglemaximizescreen,
binds=SUPER,f,togglefullscreen,
binds=SUPER+SHIFT,f,togglefakefullscreen,
binds=SUPER,i,minimized,
binds=SUPER,o,toggleoverlay,
binds=SUPER+SHIFT,I,restore_minimized
binds=SUPER,z,toggle_scratchpad

# tag switch
binds=ALT,Left,viewtoleft,0
binds=ALT+SHIFT,Left,viewtoleft_have_client,0
binds=ALT,Right,viewtoright,0
binds=ALT+SHIFT,Right,viewtoright_have_client,0
binds=ALT+SUPER,Left,tagtoleft,0
binds=ALT+SUPER,Right,tagtoright,0

binds=ALT,ampersand,view,1,0
binds=ALT,eacute,view,2,0
binds=ALT,quotedbl,view,3,0
binds=ALT,apostrophe,view,4,0
binds=ALT,parenleft,view,5,0
binds=ALT,minus,view,6,0
binds=ALT,egrave,view,7,0
binds=ALT,underscore,view,8,0
binds=ALT,ccedilla,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=ALT,1,tagsilent,1
binds=ALT+SUPER,ampersand,tag,1,0
binds=ALT+SUPER,eacute,tag,2,0
binds=ALT+SUPER,quotedbl,tag,3,0
binds=ALT+SUPER,apostrophe,tag,4,0
binds=ALT+SUPER,parenleft,tag,5,0
binds=ALT+SUPER,minus,tag,6,0
binds=ALT+SUPER,egrave,tag,7,0
binds=ALT+SUPER,underscore,tag,8,0
binds=ALT+SUPER,ccedilla,tag,9,0

# monitor switch
binds=CTRL+SHIFT,Left,focusmon,left
binds=CTRL+SHIFT,Right,focusmon,right
binds=CTRL+SUPER,Left,tagmon,left
binds=CTRL+SUPER,Right,tagmon,right

# gaps
binds=ALT+SHIFT,X,incgaps,1
binds=ALT+SHIFT,Z,incgaps,-1
binds=ALT+SHIFT,R,togglegaps

# movewin
# binds=CTRL+SHIFT,Up,movewin,+0,-50
# binds=CTRL+SHIFT,Down,movewin,+0,+50
# binds=CTRL+SHIFT,Left,movewin,-50,+0
# binds=CTRL+SHIFT,Right,movewin,+50,+0

# resizewin
binds=SUPER+CTRL,Up,resizewin,+0,-10
binds=SUPER+CTRL,Down,resizewin,+0,+10
binds=SUPER+CTRL,Left,resizewin,-10,+0
binds=SUPER+CTRL,Right,resizewin,+10,+0

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize

# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
# axisbind=SUPER,DOWN,viewtoright_have_client
