##############################
#                            #
#          Gestures          #
#                            #
##############################

# 3-finger: Window focus
gesturebind=none,left,3,focusdir,right
gesturebind=none,right,3,focusdir,left
gesturebind=none,up,3,focusdir,up
gesturebind=none,down,3,focusdir,down
