##############################
#                            #
#            Rules           #
#                            #
##############################

# Tag 1 : shell / terminaux / Perplexity
windowrule=tags:1,scroller_proportion:1,appid:kitty-1
# windowrule=tags:1,scroller_proportion:0.5,appid:perplexity
# windowrule=tags:1,scroller_proportion:0.5,appid:kitty-2

# Tag 2 : web
windowrule=tags:2,scroller_proportion:0.8,appid:chromium
windowrule=tags:2,appid:firefox

# Tag 6 : web
windowrule=tags:6,scroller_proportion:1,appid:kitty-mon

# Tag 7 : web
windowrule=tags:7,scroller_proportion:1,appid:chrome-hnpfjngllnobngcgfapefoaidbinmjnm-Default

# Tag 8 : mail
windowrule=tags:8,scroller_proportion:0.5,appid:proton-bridge
windowrule=tags:8,scroller_proportion:1,appid:org.mozilla.Thunderbird

# Tag 9 : musique
# adapte la valeur d'appid à ce que ton script affiche pour Spotify
windowrule=tags:9,scroller_proportion:1,appid:Spotify

windowrule=isfloating:1,width:800,height:600,offsetx:0,offsety:0,appid:blueman-manager
windowrule=isnamedscratchpad:1,width:1000,height:700,appid:Proton Pass

# layer rule
layerrule=animation_type_open:slide,layer_name:wofi
layerrule=animation_type_close:slide,layer_name:wofi

# Specifics rules
windowrule=scroller_proportion:0.5,appid:kitty-yazi
