#!/bin/sh
# Environnement XDG propre, GREETD_SOCK hérité pour le protocole IPC.
export HOME=/var/lib/labfy-greeter
export XDG_CONFIG_HOME=/var/lib/labfy-greeter/config
export XDG_STATE_HOME=/var/lib/labfy-greeter/state
export XDG_CACHE_HOME=/var/cache/labfy-greeter
exec /usr/bin/sway --config /etc/greetd/labfy-sway.conf
