#"$schema" = 'https://starship.rs/config-schema.json'
format = """
$os$username$hostname$directory$git_branch$git_status$python$lua$rust$php$nodejs${custom.venv}
$character
"""
right_format = """
$time$battery
"""
add_newline = true

palette = "catppuccin_mocha"

[[battery.display]]
threshold = 30
style = 'bold red'

[aws]
symbol = " "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "

[cpp]
symbol = " "

[cmake]
symbol = " "

[conda]
symbol = " "

[container]
format = '[$symbol \[$name\]]($style) '

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[directory]
read_only = " 󰌾"
truncation_length = 3
truncation_symbol = '…/'

[docker_context]
symbol = " "

[env_var.SHELL]
variable = 'SHELL'
default = 'unknown shell'

[env_var.USER]
default = 'unknown user'

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fortran]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
disabled = false
ssh_only = false
format = "[@$hostname]($style) "
style = "bold lavender"
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[localip]
ssh_only = false
format = '@[$localipv4](bold red) '
disabled = false

[lua]
symbol = " "
format = 'via [ $version](bold blue) '

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
format = 'via [ $version](bold green) '

[ocaml]
symbol = " "

[os]
disabled = false
format = "[$symbol]($style)-"
style = "bold lavender"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "
format = 'via [ $version](147 bold) '

[pijul_channel]
symbol = " "

[pixi]
symbol = "󰏗 "

[python]
symbol = " "
style = "bold yellow"
format = '[$symbol($virtualenv )]($style) '
python_binary = ["./.venv/bin/python", "python", "python3"]

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "
format = 'via [󱘗  $version](red bold)'

[scala]
symbol = " "

[shell]
fish_indicator = '󰈺 '
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
style = 'lavender'
disabled = false

[status]
symbol = " "

[swift]
symbol = " "

[time]
disabled = false
format = "[$time]($style) "
time_format = "%H:%M"        # 24h, heures:minutes
style = "blue"

[username]
disabled = false
show_always = true
format = "[$user]($style)"
style_user = "bold lavender"
style_root = "bold red"

[custom.venv]
command = "echo VENV-ACTIVE"
when = '[[ -n "$VIRTUAL_ENV" ]]'
format = '[ $output ](bold red) '

[xmake]
symbol = " "

[zig]
symbol = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
