##################################
#                                #
#       Generals settings        #
#                                #
##################################

# Couleurs correctes pour neovim
set -g default-terminal "screen-256color"

# Souris (sélection, scroll, resize des panes)
set -g mouse on

# Historique large
set -g history-limit 100000

# Temps d'attente après Ctrl+b (en ms)
set -s escape-time 10


##################################
#                                #
#              Style             #
#                                #
##################################

# Barre simple sans plugin
set -g status-bg colour238
set -g status-fg colour255
set -g status-left-length 40
set -g status-right-length 80

# Gauche : [session] fenetre:pane
set -g status-left '#[bold] #S #[default]#I:#P '

# Droite : user@host | path | heure
set -g status-right '#(whoami)@#H | #{pane_current_path} | %H:%M '

##################################
#                                #
#            Shortcuts           #
#                                #
##################################

unbind C-b
set -g prefix C-x
bind C-x send-prefix

# 4. Reload config avec prefix + r
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

unbind '"'
unbind %

# leader + h : split horizontal (pane en haut/bas)
bind h split-window -v
# leader + v : split vertical (pane gauche/droite)
bind v split-window -h

set -g @catppuccin_flavor 'mocha'

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-position top
set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_lavender}] #(whoami)@#H | #{pane_current_path} | %H:%M | session: #S '
set -g status-right-length 120
set -g status-left '#[fg=#{@thm_teal},bg=#{@thm_lavender},bold] #S #[fg=#{@thm_crust},bg=#{@thm_lavender}] #I:#W #[default]'
set -g status-left-length 120
