# ===== Apparence générale =====
font_family                     JetBrainsMono Nerd Font
font_size                       12.0
enable_audio_bell               no
hide_window_decorations         yes
allow_remote_control            yes

# Behaviour
url_prefixes                    http https gemini
url_style                       single
strip_trailing_spaces           smart
linux_display_server            wayland

# Cell Configuration
adjust_line_height              1
adjust_column_width             1

# Tab Bar  
tab_bar_edge                    top
tab_bar_style                   powerline
tab_separator                   ❯
active_tab_font_style           normal

# Cursor
cursor_blink_interval           -1
cursor_shape                    block
cursor_blink_interval           0.5
cursor_stop_blinking_after      0
cursor_trail                    0
shell_integration               no-cursor

include kitty-themes/themes/mocha.conf
